### ISSUE TITLE
Wrap contents of template around selected text 

### ISSUE THREAD

**Issue by johans3** [Vinzent03/obsidian-hotkeys-for-templates#13]
I'd love if *shortcuts for templates* could paste and wrap contents of templates around our selected text in edit mode.
Is this possible?

**Comment by Vinzent03** [comment]
Sorry for the late reply. You mean you want to replace the selected text with the selected template? That should already be the case. Otherwise, I don't really understand your question.

**Comment by johans3** [comment]
It's OK
I've collected some smaller bits of HTML code to highlight selected text,

Therefore I was wondering if i could select some text and then, press a shortcut to highlight the same text using the template code.

Of course the template shouldn't erase my text and replace it with the highlight code, but add the template like two brackets around my text

**Comment by FelipeRearden** [comment]
Hello @johans3 !

I’m gonna try to help: if I understood correctly, this plug-in Multi. Line Formatting do what you are asking for 

https://github.com/nmady/obsidian-multi-line-formatting

Sorry if I didn’t understood your FR.

Have a great day!

**Comment by Vinzent03** [comment]
If that's what @johans3 was searching for I can close this issue right?

**Comment by johans3** [comment]
> If that's what @johans3 was searching for I can close this issue right?

I got my highlight feature, so if course I'm happy. But templates usually are not conceived to highlight colors, this was merely my work around. 

Anyway, my original question was, 
if your plugin is able to insert new templates without removing any selected text. But incorporate the selected text  

Your plugin works well, but my suggestion could improve the use of your plugin, I guess.
It's OK for me if you want to close this ticket.

**Comment by Vinzent03** [comment]
But where should the selected text go after the replace? That's more an issue for the template service itself. Like Templater or the core plugin.

**Comment by Vinzent03** [comment]
I am just calling the template insert function at the according plugin. I am not actually parsing the template myself.

**Comment by johans3** [comment]
Nevermind, your plugin is also useful without parsing-maybe you can implement variables in future
