### ISSUE TITLE
New file creation along with tp.file.move/tp.file.rename results in extra empty file

### ISSUE THREAD

**Issue by OfficerHalf** [Vinzent03/obsidian-hotkeys-for-templates#15]
I have the following template. It's got a little bit of templater script at the bottom to update a value in the template and move/rename the output file. It doesn't matter if I use `tp.file.move` or `tp.file.rename`, in both cases, no matter the output path configured for the new file hotkey, I end up with an extra empty `Untitled.md` note. This extra note *does not* get created if using the `Templater: Create new note from template` command and selecting the same output folder as the hotkey.

```markdown
---
metatable: true
title: Untitled
campaign: Curse of Strahd
session: 005
session_date: <% tp.date.now("MM.DD.YYYY") %>
tags: RPG/CurseOfStrahd, RPG/SessionNotes/DM
notes_folder: "/RPGs/Curse of Strahd/Meta/Session Notes/"
---
# `= this.title`

⬅ [[|Last Session]] / [[|Next Session]] ➡
**date:** `= this.session_date`
**PC:** [[Anton (Valros)|Anton]], [[Lucky Tenny]], [[Viktor Voronkov]], [[Zoe]]
**NPC Active:**
**NPC Discussed:**
**Location Active:**
**Location Discussed:**
**Monsters:**

## Post session notes

## To do before next session

## Soon

<%*
const frontmatter = this.app.metadataCache.getFileCache(tp.config.template_file)?.frontmatter;
const {update} = this.app.plugins.plugins["metaedit"].api;
// Get current session number, next session number
const oldNumber = frontmatter.session;
const newNumber = `${oldNumber + 1}`.padStart(3, '0');
const oldNumberPadded = `${oldNumber}`.padStart(3, '0');

// Update title of new file
let title = tp.file.title;
if (title.startsWith("Untitled")) {
  title = `S${oldNumberPadded} ${tp.date.now("MM.DD.YYYY")}`;
  await tp.file.rename(`${title}`);
}

// Update session number in template
await update('session', newNumber, tp.config.template_file);
%>
```

The extra file ends up in the folder specified in the hotkey.

**Comment by Vinzent03** [comment]
Sorry, but I can't reproduce. Does it happen if you short it to the following, too?
```js
<%*
await tp.file.rename('foo');
%>
```

**Comment by OfficerHalf** [comment]
@Vinzent03 yeah, I was seeing it super consistently with your plugin but not the base templater when I was initially testing it, so I opened this. But now I'm sometimes seeing similar behavior with other templater things unrelated to your plugin. I expect its either Windows/OneDrive causing me issues, maybe Sync, or maybe just something with templater. Can close this.
