### ISSUE TITLE
Invoke with Tab

### ISSUE THREAD

**Issue by Calorion** [Vinzent03/obsidian-hotkeys-for-templates#19]
This plugin is awesome. Is there a way to invoke it using only the Tab key? I want to replace the default Tab function with $\qquad$.

**Comment by Vinzent03** [comment]
Since I'm using Obsidian hotkeys system, and they don't support just the tab key, this doesn't work currently. But I don't want to create my own key listeners and stuff, so this feature is not currently planned. Sorry.
