### ISSUE TITLE
Error upon opening: Failed to load plugin obsidian-hotkeys- for-templates

### ISSUE THREAD

**Issue by eb2ai** [Vinzent03/obsidian-hotkeys-for-templates#22]
I reviewed issue #21, thinking I had the same issue, but this appears to be something different. I have my template directory defined in the core templates plugin and also the templater plugin.  I keep my templates in `Setup/templates`, which may be a little unusual, so I changed it to just `templates` for testing purposes but have the same issue.

This has been working for a very long time. I am now running the latest pre-release, so there may have been a config change in the core app. >shrug<

I should also note that I completely removed the plugin and ensured the plugin directory was removed and reinstalled... just in case there was some syncing funny business going on.

Upon loading Obsidian, I get the following error.
![Screenshot 2023-10-05 at 05 11 47](https://github.com/Vinzent03/obsidian-hotkeys-for-templates/assets/134644662/84de2e81-55b6-4ebd-8eeb-5cefb43edf6b)

If I examine the console, I see.
![Screenshot by Dropbox Capture](https://github.com/Vinzent03/obsidian-hotkeys-for-templates/assets/134644662/bba11138-e328-4c62-a08f-a3e18ad8af88)

App Version
![Screenshot by Dropbox Capture](https://github.com/Vinzent03/obsidian-hotkeys-for-templates/assets/134644662/d3c241fc-0639-418a-9f0e-98f7000e7d6c)

Thanks for the great plugin.

**Comment by Vinzent03** [comment]
Somehow the plugin `settings-search` is included in the stacktrace. May you try disabling it and restarting Obsidian?

**Comment by eb2ai** [comment]
Good catch, I'm sorry I missed that line. I think they updated that problem in settings search with a recent update.  Thanks for the response.
