### ISSUE TITLE
[Feature request] Create note in a given folder from template

### ISSUE THREAD

**Issue by ShreyasKallingal** [Vinzent03/obsidian-hotkeys-for-templates#3]
Would it be possible to allow hotkeys to create a new note in a specified folder from a given template? For example, this would allow me to create a new "task" note in 1 shot. Thanks!

**Comment by Vinzent03** [comment]
Good idea. I guess I will work on it tomorrow.

**Comment by Vinzent03** [comment]
Sorry for the late answer and implementation. I was very busy with [obsidian-git](https://github.com/denolehov/obsidian-git)

**Comment by ShreyasKallingal** [comment]
Absolutely no worries—less than 10 days is ridiculously fast in my book. The UI is very slick, and it works great. Thank you very much :)
