### ISSUE TITLE
After changing/removing "Add new note" entry, hotkey still available

### ISSUE THREAD

**Issue by Moonbase59** [Vinzent03/obsidian-hotkeys-for-templates#6]
I used "add new text field" to enter Folder=`People` and Template=`Templater: Character`, then later changed it to Folder=`People/Friends & Family`, Template=`Templater: Character`.

Under _Settings → Hotkeys_, it now still shows _both_:

![Auswahl_023](https://user-images.githubusercontent.com/3706922/119179399-27650480-ba6f-11eb-99e8-2bb2e9512910.png)

Using Obsidian 0.12.3 on Linux, Hotkeys for templates 1.2.1, Templater 1.6.0.

Only after restarting Obsidian, the Hotkeys entries are shown correctly again.

**Comment by Vinzent03** [comment]
I am aware of this issue, should be an easy fix.

**Comment by Moonbase59** [comment]
Confirm fixed in 1.2.2. Thanks!
