### ISSUE TITLE
Feature Request: Possible to trigger new templated note WITHOUT using a hotkey or command?

### ISSUE THREAD

**Issue by Moonbase59** [Vinzent03/obsidian-hotkeys-for-templates#7]
Just asking: Since we can enter folder/template pairs already to specify which template should be used for which file when creating a new note, would it be possible to have this _when not using a hotkey or command palette command?_

For example, I would create a new file using the Obsidian functions (Ctrl+N, right-click in file explorer and select "New Note" or the like) _within a folder that is specified in the plugin settings_, could it then also _automatically intervene and apply the specified template?_

This would make it _so much more usable_ (we only have so many keys …), by just _always_ creating a templated new note within specified folders!

**Comment by Vinzent03** [comment]
I would need to change an internal function in Obsidian, which I really don't want to. It could cause some strange side effects. And adding an extra command for this, is not enough, because there are many ways to create a new file.

**Comment by Moonbase59** [comment]
Ah okay, thanks for the heads-up!

**Comment by Vinzent03** [comment]
I have found a solution after all. Will do it now.

**Comment by Moonbase59** [comment]
Wow, this is impressive and really helpful, thanks!

Q: Seems you use the same construct as _Templater_ does (react on new file creation in vault). Would this conflict with _Templater_ if I set _both_ to "Trigger on new file creation"?

(And thanks for adding that switch!)

**Comment by Moonbase59** [comment]
Another find:

I naively expected "Folder" to mean "this and all its subfolders", so if I have
- folder "People" assigned to "Template A"
- folder "People/Friends & Family" assigned to "Template B"

the following would happen:
- New note in "People" → Template A
- New note in "People/Notable" → Template A
- New note in "People/Friends & Family" → Template B (instead of Template A, because the definition is more specific)

This is from a usability standpoint: I may have, say, a "People" folder with "Friends & Family" and "Notable" subfolders. I would want to use the same template (A) for all kinds of "People", even if I created many new subfolders (without having to specify them all). Or I might rename a few subfolders and wouldn’t have to re-specify them all.

Then I would need a special Template (B) for "People/Friends & Family", so I specify it in settings. This would be applied instead of template A because the path is more specific. And it would also work for subfolders within "People/Friends & Family".

Could this be done? I guess some people might be quite happy about it. :-) (Yes, me too!)
Path "specificity" shouldn’t be too hard to establish, I think.

**Comment by Vinzent03** [comment]
> Would this conflict with Templater if I set both to "Trigger on new file creation"?

I wouldn't suggest you to enable both features. The filename for a new file is always `Untitled`, why else did you expect?

Will see what I can do for your folder problem

**Comment by Moonbase59** [comment]
Unfortunately, I do need Templater’s trigger to be also enabled (mainly for "New file from template", where I need the template to be executed in places not defined in _Hotkeys for templates_). But you are right, any file first gets created as "Untitled", so using that Templater variable was probably dumb. :rofl: I must have been thinking it was only done _after_ assigning a name. My mistake.

Thanks a bundle for implementing the new file triggering and looking into the path thing, greatly appreciate it!

**Comment by Vinzent03** [comment]
Is available in new release!

**Comment by Moonbase59** [comment]
Perfect, works great! Thanks again!
