### ISSUE TITLE
Applies the template twice

### ISSUE THREAD

**Issue by bibek-maharjan** [Vinzent03/obsidian-hotkeys-for-templates#9]
When "Trigger on file creation" is active and a hotkey is specified for a new file in a specified folder, upon pressing the hotkeys, the template gets applied twice. I don't want to add hotkey for certain folder but simply enable trigger template on creation whereas I use hotkey for some folders for new note creation.
![image](https://user-images.githubusercontent.com/76084262/126772932-e4aecee7-c09b-4e42-8d69-079504238d98.png)

**Comment by Vinzent03** [comment]
So you want the hotkey template to overwrite the template on file creation?

**Comment by bibek-maharjan** [comment]
Yes :)
